language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install -v

script: poetry run pytest -q tests/
