name: "Check new tz data on iana site"
#on:
#  schedule:
#  - cron: "*/2 * * * *"

on: workflow_dispatch

jobs:
  check_iana:
    name: Check url response
    runs-on: ubuntu-latest
    steps:
      - name: run curl
        run: if [ "$(curl -s -I -o /dev/null -w '%{http_code}' https://data.iana.org/time-zones/releases/tzdata2023c.tar.gz.asc)" -eq '200' ]; then false; else true; fi;
